"""add scheduled

Revision ID: 0153a7966104
Revises: e7cb9884d233
Create Date: 2024-03-16 02:50:38.726817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0153a7966104'
down_revision: Union[str, None] = 'e7cb9884d233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos_table', sa.Column('scheduled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos_table', 'scheduled')
    # ### end Alembic commands ###
